version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  users:
    build:
      context: ./users
    environment:
      DATABASE_URL: mysql://root:root@database:3306/app
    depends_on:
      - database
    ports:
      - "8001:8000"

  notifications:
    build:
      context: ./notifications
    depends_on:
      - database
    ports:
      - "8002:8000"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  db_data:
